version: "3.9"

name: "rails-demo"

services:
  web:
    build: .
    command: bin/rails server -b 0.0.0.0
    env_file: .env
    volumes:
      - .:/rails
    links:
      - postgres
    ports:
      - "3000:3000"
