version: "3.9"

name: "rails-demo"

services:
  web:
    build: .
    command: bin/rails server -b 0.0.0.0
    env_file: .env
    volumes:
      - .:/rails
    links:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres:16.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgresql-data:/var/lib/postgresql/data
