service: rails-demo

image: owalmirneto/rails-demo

servers:
  - 34.203.9.4

registry:
  server: registry.gitlab.com
  username:
    - GITLAB_REGISTRY_USERNAME
  password:
    - GITLAB_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - RAILS_DEMO_DATABASE_URL

ssh:
  user: ubuntu
