name: Feature code review

on:
  pull_request:
    branches: [main]

jobs:
  standardrb:
    name: StandardRB
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: default
          ruby-version: 3.2.3
          bundler-cache: true

      - name: Verify ruby version
        run: ruby --version

      - name: Bundle install
        run: gem install bundler -v '~> 2.5' && bundle install --jobs 4 --retry 3

      - name: Run StandardRB
        run: bin/standardrb
