name: Feature code review

on:
  pull_request:
    branches: [main]

jobs:
  brakeman:
    name: Brakeman
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: default
          ruby-version: 3.2.3
          bundler-cache: true

      - name: Verify ruby version
        run: ruby --version

      - name: brakeman
        uses: reviewdog/action-brakeman@v2
        with:
          brakeman_version: 6.1.2

  code-style:
    name: Check code style
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: default
          ruby-version: 3.2.3
          bundler-cache: true

      - name: Verify ruby version
        run: ruby --version

      - name: Install Bundler
        run: gem install bundler -v 2.5.5

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run Standard Ruby
        run: bin/standardrb

      - name: Run ERB Lint
        run: bin/erblint app --format compact

  rspec:
    name: RSpec
    runs-on: ubuntu-22.04
    permissions: write-all

    env:
      APP_NAME: RailsDemo
      DATABASE_HOSTNAME: localhost
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: rails_test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/rails_test

    services:
      db:
        image: postgres:16.0-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: default
          ruby-version: 3.2.3
          bundler-cache: true

      - name: Verify ruby version
        run: ruby --version

      - name: Install Bundler
        run: gem install bundler -v 2.5.5

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Precompile assets
        run: bin/rails assets:precompile

      - name: Prepare database
        run: bin/rails db:setup db:test:prepare db:schema:load db:migrate

      - name: Run RSpec
        run: bin/rspec

      - name: Check code coverage
        uses: joshmfrankel/simplecov-check-action@main
        with:
          minimum_suite_coverage: 100
          minimum_file_coverage: 100
          github_token: ${{ secrets.GITHUB_TOKEN }}
